### PR TITLE
[D2R UI Fixes] added settings toggles

### PR DESCRIPTION
**Pull request by Caedendi**

### CODE REVIEW

**Comment by jesuscc1993** [comment]
I suppose you added the toggles because either or both of them conflicted with some other mod.
And that you added the build function to isolate the otherwise loose code.
What I don't get is why you added the classes; what reason did you have to?
The way I see it they only add extra unnecessary complexity.
_Edit:_ I know it's not _much_ added complexiy, but it feels like _pointless_ complexity.

**Comment by Caedendi** [comment]
I get what you mean and I'll revert that if prefer it.

It's part of my standard refactoring flow whenever I'm tinkering with D2RMM mods, I come from an object-oriented background so I prefer using classes. I'm not really used to functions being constants and other such JS practices, it feels weird to me.

**Comment by jesuscc1993** [comment]
If that's fine, I can clone your branch and attempt doing the refactor myself.
And then you can test if the updated code works; I no longer have the game installed and I don't really feel like installing it just to test this.

**Comment by Caedendi** [comment]
Either is fine with me, tho it may take a while before I can find the time to do so.

**Comment by jesuscc1993** [comment]
@Caedendi I have updated the PR; let me know if it works on your end once you get the chance to test it.

**Comment by Caedendi** [comment]
@jesuscc1993 Apologies for the delay. Your changes look good and seem to work on my end!

**Pull request merged**
